### ISSUE TITLE
希望编写Android Studio插件，方便快速生成手脚架，方便应用

### ISSUE THREAD

**Issue by destinyd** [lizixian18/EasyMvp#1]

**Comment by EspoirX** [comment]
可以

**Comment by longforus** [comment]
厚脸皮推荐一下我的插件,这个框架应该可以用,真的是意外看见,完全没有要拆台的意思.....

**Comment by EspoirX** [comment]
插件叫啥，给我参考参考啊

**Comment by destinyd** [comment]
[java版的](https://www.kancloud.cn/alex_wsc/android_library_framework/452651)

[kotlin版的](https://github.com/y1xian/KotlinMvp)

**Comment by EspoirX** [comment]
谢谢哈
