### ISSUE TITLE
网络请求

### ISSUE THREAD

**Issue by sunzhenyong** [lizixian18/EasyMvp#2]
=

**Comment by EspoirX** [comment]
完全可以结合，这个是在 P 层和 Model 层自己的逻辑，至于网络请求和RxJava生命周期，完全可以在 绑定View 和 解绑 View 的方法里面去做。

**Comment by Vension** [comment]
感觉棒棒哒，希望持续维护下去，感谢开源

**Comment by sunzhenyong** [comment]
要是有一套结合网络请求的就nice了

**Comment by EspoirX** [comment]
有空加个这方面的例子吧
