### ISSUE TITLE
项目混淆后，运行报错

### ISSUE THREAD

**Issue by dicallc** [lizixian18/EasyMvp#3]
项目混淆后，运行报错

**Comment by EspoirX** [comment]
里面有用到反射和注解，你可以查查这两个在混淆后是不是会有影响

**Comment by dicallc** [comment]
我看了，是有影响的，就是不知道该怎么写混淆规则.....很尴尬，项目快上线，楼主能提供下混淆规则嘛

**Comment by EspoirX** [comment]
我也没试过，keep住那些mvp基础类试试。。我晚点查查资料。

**Comment by dicallc** [comment]
不行哦，keep住了Presenter是空的

**Comment by dicallc** [comment]
暂时不用@PresenterVariable注解，用getPresenterProviders().getPresenter(0);没出问题了

**Comment by EspoirX** [comment]
因为这个注解里面用到了反射，我还没时间去查资料，你有空查查混淆和这方面相关的吧

**Comment by EspoirX** [comment]
如果你只有一个Presenter的话，其实你这样就好了：
```
@CreatePresenter(presenter = LoginPresenter.class)
public class ExampleActivity3 extends BaseMvpActivity<LoginPresenter> implements LoginView {

    @Override
    protected int getContentView() {
        return R.layout.activity_main;
    }

    @Override
    public void init() {
        getPresenter().login();
    }

    @Override
    public void loginSuccess() {
        Log.i("ExampleActivity1", "登陆成功");
    }
}
```

**Comment by dicallc** [comment]
嗯，好，主要是我在混淆这方面对于反射和注解，也了解的不多，如果后期知道了，还是加上吧

**Comment by zilianliuxue** [comment]
加上这2个注解类的混一下就好了
-keep @packagename.PresenterVariable class * {*;}
-keep @packagename.CreatePresenter class * {*;}
-keep class * {
    @packagename.PresenterVariable <fields>;
    @cpackagename.CreatePresenter <fields>;
}
-keepclassmembers class ** {
    @packagename.PresenterVariable <methods>;
    @cpackagename.CreatePresenter <methods>;
}

**Comment by EspoirX** [comment]
老铁666，等下我写到 readme 里，thanks

**Comment by dicallc** [comment]
@lizixian18  最好写一个范例，我刚刚按照写得时候，编译失败了

**Comment by EspoirX** [comment]
不会失败啊，额……大括号里面分号前要加个星号

**Comment by dicallc** [comment]
是这样的么？ 
<pre>
-keep com.abc.abc.utils.mvp.PresenterVariable class * {*;}
-keep com.abc.abc.utils.mvp.CreatePresenter class * {*;}
-keep class * {
 com.abc.abc.utils.mvp.PresenterVariable;
 com.abc.abc.utils.mvp.CreatePresenter;
 }
-keepclassmembers class ** {
 com.abc.abc.utils.mvp.PresenterVariable;
 com.abc.abc.utils.mvp.CreatePresenter;
 }
<pre>

能帮我喵喵不~

**Comment by EspoirX** [comment]
运行下不蹦就是可以了

**Comment by dicallc** [comment]
@zilianliuxue  按照你写的一直编译失败，能帮我看看不，或者留个联系方式请教一下

**Comment by yswheye** [comment]
@dicallc 这样写
![image](https://user-images.githubusercontent.com/7885990/47206711-e6d71300-d3bb-11e8-8c74-9d0fb253ad9c.png)

**Comment by yswheye** [comment]
@lizixian18 需要这样写才行，readme要更新下了。
![image](https://user-images.githubusercontent.com/7885990/47206768-0e2de000-d3bc-11e8-9227-458dc9771a77.png)

**Comment by EspoirX** [comment]
好，谢谢

**Comment by solochen** [comment]
如果还有不能编译的朋友可以这样配：

-keep class xx.xx.xx.PresenterVariable {*;}
-keep @xx.xx.xx.PresenterVariable class *
-keep class xx.xx.xx.CreatePresenter {*;}
-keep @xx.xx.xx.CreatePresenter class *
-keep class * {
   xx.xx.xx.PresenterVariable <fields>;
   xx.xx.xx.CreatePresenter <fields>;
}
-keepclassmembers class ** {
   xx.xx.xx.PresenterVariable <methods>;
   xx.xx.xx.CreatePresenter <methods>;
}
