### ISSUE TITLE
Presenter的创建只能是一个无参的构造函数

### ISSUE THREAD

**Issue by yuantang** [lizixian18/EasyMvp#4]
![image](https://user-images.githubusercontent.com/6096784/46929028-20ccb000-d070-11e8-81e3-5175d1521224.png)
Presenter只能是一个无参的构造函数，可以优化成可以带参的就好了。

**Comment by EspoirX** [comment]
是的，你需要多参数的？你可以说说多参数是什么情况下需要？因为上下文已经有了。

**Comment by yuantang** [comment]
开始我是将bindLifecycle的对象通过Presenter中获取的，需要一个带参的构造函数，但是这个框架只能是一个无参的构造。现在我换了一个思路，放在了view中去获取也是可以的。

**Comment by EspoirX** [comment]
像BasePresenter里面的Content那样做就行。需要的时候get出来就好

**Comment by EspoirX** [comment]
![image](https://user-images.githubusercontent.com/16240767/46940672-da8d4600-d09b-11e8-8224-c9fb09e1d72a.png)

**Comment by yuantang** [comment]
恩恩。。
