### ISSUE TITLE
发现一个问题presenter=null

### ISSUE THREAD

**Issue by yswheye** [lizixian18/EasyMvp#5]
![image](https://user-images.githubusercontent.com/7885990/47205477-9d38f900-d3b8-11e8-84c4-f02c169998bc.png)
mvp代码放在common这个module里，
在另一个module里引用common，使用mvp。
发现通过@PresenterVariable注解获取的presenter为null，而getPresenterProviders().getPresenter(0)获取的是可以的。
同样的在app 主module下使用注解获取是没有问题的。
问题出在哪？

**Comment by yswheye** [comment]
看了closed issue，已解决。

**Comment by EspoirX** [comment]
是什么问题？混淆吗
